### ISSUE TITLE
radix_tree_init Undefined reference

### ISSUE THREAD

**Issue by zhuyaliang** [kdave/btrfs-progs#205]
```
#include <btrfs/radix-tree.h>
int main (void)
{
	radix_tree_init ();
}
```
>gcc main.c -lbtrfs

>In the function'main':
main.c:(. text + 0x5): An undefined reference to'radix_tree_init'
collect2: error: ld returned 1 exit status

**Comment by zhuyaliang** [comment]
The API was exposed but there was no corresponding implementation in the connection Library

**Comment by zhuyaliang** [comment]
Similarly, APIs in ``` btrfs/extent-cache.h``` files cannot be found in static libraries

**Comment by kdave** [comment]
Right, the objects are missing. Please note that the static library is not in a state to be considered usable for everything, it's original purpose was to provide the send/receive functionality. Also the license is not LGPL but just GPL so ti's not clean for linking.

I'll fix the build in case it's fine for you to use it despite the licensing, otherwise the libbtrfsutil should be used for new projects. The fate of `libbtrfs` is undecided so it will stay for the time beging.

**Comment by kdave** [comment]
The fix is to add remaining object files that match the headers:
* radix-tree.o
* extent-cache.o
* extent_io.o
