### ISSUE TITLE
Feature request: Zstd adaptive compression rates

### ISSUE THREAD

**Issue by RubenKelevra** [kdave/btrfs-progs#242]
Zstd is able to do an adaptive compression rate selection, depending write speed. So if a file can be faster written than compressed zstd will reduce the compression level.

It would be nice to have this feature in btrfs.

**Comment by kdave** [comment]
I think there are too many variables and I'm not sure what would be the typical usecase for that. The result of auto-tuning would depend on external factors like system load, device speed. An occasional hickup or spike in load leads to worse compression ratio, which in the end becomes unpredictable. The expected behaviour (as I understand it) should be predictable - compress on level 3 will really do only this.
The tuning based on write speed needs some sort of feedback loop, check if the write is fast enough (allow faster compression) or the other way around. This is technically possible but it starts to sound like optimizing for the "output" parameter, while everything so far we have is on the "input" side, ie. let the user chose first.
Seasoned admins often want all the knobs and no automatic behaviour, while there's another large group of users that have less specific goals, like "try to submit IO as fast as the device writes, compress at need".
Another problem might be the way how specify which files should be compressed by the fixed level and which by the adaptive level.

So before implementing this, we'd need the usecase description and expectations specified in more detail.

I personally use the compression in 2 ways: real-time with low ratio but unnoticeable cpu/speed impact, and archiving, where the compression ratio is the important part. The exact real-time level can be determined by some benchmarking, on a machine with fast and many cpus a higher compression level will be unnoticeable and the slowing factor would be typically the storage. Tuning for extra fast storage requires benchmarking. I hope current compression tunables provide enough flexibility for most users, for specific usecases we need to do the cost/benefit analysis.
