### ISSUE TITLE
Curious about btrfs bugs noted in "Finding Bugs in File Systems with an Extensible Fuzzing Framework"

### ISSUE THREAD

**Issue by mjhurd** [kdave/btrfs-progs#248]
https://dl.acm.org/doi/abs/10.1145/3391202

Just curious as I'm a relatively happy user of btrfs over mdadm raid and thankful to the btrfs community for a good fs that supports lightweight compression. 

I read "Meanwhile, the other consistency issues in Btrfs are not patched yet" and "For example, we
found a case in Btrfs (Figure 1) that could cause irrecoverable data loss in the event of power loss
or system crashes, which can be disastrous for data centers." Noting something as "disastrous" seems a little unbecoming in a research paper, but there you go.   

They tested on ubuntu 16.04 so not exactly the latest and greatest but they claim the issues, if they are such, remain unfixed. 

Any thoughts?

**Comment by kdave** [comment]
Thanks for the link to the article. The people behind it are from Georgia Institute of Technology and you can find the reports and fixes in the mailinglist. The applied patches usually track the reporter and bugs, grep the git logs for `@gatech.edu`.

A few examples:
* https://git.kernel.org/linus/6bf9e4bd6a27784 https://bugzilla.kernel.org/show_bug.cgi?id=202763
* https://git.kernel.org/linus/80e46cf22ba0 https://bugzilla.kernel.org/show_bug.cgi?id=202765
* https://git.kernel.org/linus/ab4ba2e133463c70 https://bugzilla.kernel.org/show_bug.cgi?id=202691
* https://git.kernel.org/linus/448de471cd4cab (fixes several separate bug reports)

About the 'not yet', I'm not sure if there are still unfixed bugs, there are several open reports on bugzilla but against old kernel versions and bugzilla status is not always up to date. One factor could be deadline for the paper publication and development/release schedule of linux kernel. Another bugzilla triage round would tell us more.

For bugs that require a fuzzed image with crafted data that would not be created by regular use, the reports resulted in extensive sanity checks (tree-checker), so other users would be aware if the bugs should they happen.

Another class of bugs and fixes was around `fsync` combined with some file/inode changes where the semantics is clear about what's supposed to happen. The semantics are not always standardized and filesystems implement something that meets sane expectations instead of pointing to undefined behaviour.

The bug from Fig1 was fixed by https://git.kernel.org/linus/bf504110bc8aa05df4
