### ISSUE TITLE
btrfs_util_delete_subvolume requires elevated privileges

### ISSUE THREAD

**Issue by cezarmathe** [kdave/btrfs-progs#252]
btrfs_util_error btrfs_util_delete_subvolume requires elevated privileges, despite the fact that the documentation does not say that.

### Without using the lib

```bash
btrfs subvolume create ~/mytest
btrfs subvolume delete ~/mytest
```

### Using the lib

This might be a bit unconventional. I'm writing a Rust [library](https://github.com/cezarmathe/btrfsutil-rs) for using btrfsutil(through ffi). Trying to create and then delete the subvolume does not work either. I edited the source code a little to accomodate the test, I can provide more details if needed.

**Comment by kdave** [comment]
There's some history behind the subvolume deletion and it's unfortunatelly not symmetrical to the creation (ie. same user can create and delete). With mount option `user_subvol_rm_allowed` the above example would work.

Since 4.18 it's possible to delete an empty subvolume by rmdir, whether this is possible is indicated by a sysfs file `/sys/fs/btrfs/features/rmdir_subvol`.

**Comment by cezarmathe** [comment]
Is it okay if I update the PR so that it says what you have said?

>Since 4.18 it's possible to delete an empty subvolume by rmdir, whether this is possible is indicated by a sysfs file /sys/fs/btrfs/features/rmdir_subvol.

**Comment by kdave** [comment]
Yes of course.

**Comment by kdave** [comment]
Fixed in devel, thanks.
