### ISSUE TITLE
[IDEA] [CODE QUALITY] Make use of Gravity to streamline & improve the codebase

### ISSUE THREAD

**Issue by unquietwiki** [kdave/btrfs-progs#259]
I recently learned of [Gravity](https://github.com/marcobambini/gravity), which implements a small VM in C to provide some features you'd find in C++, Java, Swift, etc. This might be a way to modernize the codebase while retaining C99 kernel-code compatibility.

Edit: a quick search online says the licensing should be okay on this. Using MIT-licensed code with a GPLv2 project is apparently fine; GPLv2 code for an MIT license project is what's iffier.

**Comment by kdave** [comment]
I'm not sure we should go that way, or start adopting any other language as of now. The code base has accrued ot of cruft over the years, no question about that, but I'd first try to clean it up, in C. It's possible but not systematicly happening, the focus is almost always on new code (adding new cruft but not noticed at the time).
I had a look at gravity, but lack of the interfaces to all structures and support functionality would have to be added and it looks like writing the whole project from scratch, rather than incrementally improving it. We also need some parity with kernel code, so something will always have to be in plain old C.
Another point with a different language is what's the potential developer base, or casual user fixing a simple bug. With C it's still relatively good and has 100% overlap with the kernel developers.

**Comment by unquietwiki** [comment]
@kdave Totally understandable. Thank you for considering the idea. I keep track of stuff like this at https://www.reddit.com/r/altprog/; some of it really does seem useful, but you're absolutely right about the learning curve.

Hope you're keeping safe & well.
