### ISSUE TITLE
Including ioctl.h and ctree.h from non-GPL applications

### ISSUE THREAD

**Issue by AkihiroSuda** [kdave/btrfs-progs#380]
[`<btrfs/ioctl.h>`](https://github.com/kdave/btrfs-progs/blob/v5.10.1/ioctl.h)  and [`<btrfs/ctree.h>`](https://github.com/kdave/btrfs-progs/blob/v5.10.1/kernel-shared/ctree.h) seem to be licensed under GPL2 without any exception note.

Would it be possible to relax the license of these headers so that they can be `#include`-d from non-GPL applications?

Moby/Docker and containerd (Apache License 2.0) are already importing these headers, and I'm curious there is already a licensing concern 🤔 
- https://github.com/moby/moby/blob/v20.10.7/daemon/graphdriver/btrfs/btrfs.go#L8-L9
- https://github.com/containerd/btrfs/blob/v1.0.0/btrfs.c#L19-L20

**Comment by kdave** [comment]
The files are shared with kernel (GPL2) and are have originated from there. Changing license of existing files is tedious and for 'ctree.h' that's been there since the beginning I think it's next to impossible. As both files are mostly definitions, I'm not sure if and what problem is there regarding licenses.

For licensinsg issues there's `libbtrfsutil` that's permissive but is written from scratch and does not provide raw definitions or ioctls, but rather a clean API. However it's not complete, so it depends on what the applications need.

**Comment by AkihiroSuda** [comment]
Thanks for the quick answer!

**Comment by kdave** [comment]
The files are from `libbtrfs` which is not a proper library and is deprecated and frozen. There are very few applications using it (to my knowledge but I apparently was not aware of Moby/containerd). In the long term we want to switch 'snapper' (https://github.com/kdave/btrfs-progs/issues/218), but it works with send stream and some other structures directly so at this point the conversion can be only partial.

We'd need to identify the specific ioctls or features that the two applications and either port it to libbtrfsutil od add the missing bits.

**Comment by kdave** [comment]
You've closed it already, so in case you want to continue, please open new issues with specific requirements.
