### ISSUE TITLE
Running `mkfs.btrfs -f /dev/sda` on an older kernel fails due to BLKGETZONESZ ioctl

### ISSUE THREAD

**Issue by jkarlson** [kdave/btrfs-progs#399]
Similarly to https://github.com/kdave/btrfs-progs/issues/376 , which I understand would be fixed in v5.13?

```
++ mkfs.btrfs -f /dev/sda
btrfs-progs v5.13
See http://btrfs.wiki.kernel.org for more information.

ERROR: zoned: ioctl BLKGETZONESZ failed: Invalid argument
```

**Comment by kdave** [comment]
Yes, 5.13 hast the fix. On which version did you test it?

**Comment by jkarlson** [comment]
log says btrfs-progs v5.13 though I did not compile it myself.

If you mean kernel version, it was 3.18, 4.4, 4.9, 4.14, 4.19 failed with EINVAL. these were fairly latest .versions, I can dig exact versions, if you need them.

https://github.com/kdave/btrfs-progs/commit/6134973527a87a27b2cd9a41c8347fd4bdb74016 checks for ENOTTY, this error is presumably EINVAL.

**Comment by kdave** [comment]
This looks like a kernel problem where EINVAL could be mistakenly returned instead of ENOTTY for unknown ioctls. I found some updates regarding that in block/ioctl.c, eg. commit http://git.kernel.org/linus/732e12d805a77f74c907c0a28ece271ef1e81e01 (5.11) that seems to be end of a series cleaning up all drivers to properly distinguish between the two error codes.

EINVAL for an ioctl means the parameters are wrong, which in case ioctl(BLKGETZONESZ, &size) would be either bad file descriptor or bad address of size. Both are valid though so I think it's safe to add check for EINVAL too.

**Comment by kdave** [comment]
Fix is now in devel, could you please test it?

**Comment by jkarlson** [comment]
Thanks I did note this, but did not manage to test yet, the v5.14.1 is now in build pipeline, I will report results hopefully in coming days.

**Comment by kdave** [comment]
OK, thanks.

**Comment by jkarlson** [comment]
Fix verified on all kernels mentioned.
