### ISSUE TITLE
btrfs balance causes bad sectors?

### ISSUE THREAD

**Issue by BlueGoliath** [kdave/btrfs-progs#426]
Hi,

I noticed that my 1TB Samsung 970 Evo SSD was basically full(20GB remaining) despite me deleting many files from it. After doing some Googling, it appears that btrfs requires manual maintenance in the form of rebalancing. Upon rebalancing the root filesystem(/), it eventually failed and SMART reporrted 33 new bad sectors that did not exist before, despite the drive only being powered on for 4 months and 28 days and have a "worst" write endurance value of 99!

Currently I'm in Windows doing a surface test and it's reported bad sectors as well now too!

Is btrfs not recommended for SSDs? Is my SSD now hosed? How are you supposed to properly balanced this thing so the disk usage goes down!?!?

**Comment by Forza-tng** [comment]
Balance compacts block groups to free up unallocated space. The unallocated space is used when additional metadata or data block groups are required.

Running balance will rewrite a lot of data, so it will increase the TBW amount on SSDs. However it should not cause bad blocks unless the drive already is having problems.

If your disks is very full and you don't run regular fstrim, it will also cause a performance hit and increased TBW because the SSD has to do read-modify-write a lot.

**Comment by adam900710** [comment]
Btrfs doesn't need manual maintenance unless you have every specific usage which results unbalanced data and metadata usage.

The balance failed because of the bad sectors, not vice verse, as if you balance the full fs, it will try to read all data/metadata, which exposed the bad sectors.

Btrfs has no problem handling SSD, in fact considering btrfs is doing COW for metadata and data, in fact that provides an advantage for btrfs to even support things like zoned device (moves part of the FTL into btrfs).
And due to the COW nature, it should cause more evenly distributed write, thus reduce the wear.

It's more likely caused by bad hardware.

**Comment by adam900710** [comment]
And `nvme smart-log` should provide enough info like `data_units_written` to show the history writes of the driver.

If you really believe it's btrfs causing the wear, please provide the full `nvme smart-log` output.

**Comment by BlueGoliath** [comment]
Thanks all for the replies.

To be clear, it's not a NVME drive but a 2.5 inch drive. 

Looks like snapshots are the space issue. Deleting over half a dozen gave me 120GB(100GB?) back. Output of btrfs fi usage /:

Overall:
    Device size:		 930.07GiB
    Device allocated:		 911.04GiB
    Device unallocated:		  19.03GiB
    Device missing:		     0.00B
    Used:			 816.11GiB
    Free (estimated):		 113.00GiB	(min: 113.00GiB)
    Free (statfs, df):		 113.00GiB
    Data ratio:			      1.00
    Metadata ratio:		      1.00
    Global reserve:		 512.00MiB	(used: 0.00B)
    Multiple profiles:		        no

Data,single: Size:903.01GiB, Used:809.04GiB (89.59%)
   /dev/sda3	 903.01GiB

Metadata,single: Size:8.00GiB, Used:7.07GiB (88.38%)
   /dev/sda3	   8.00GiB

System,single: Size:32.00MiB, Used:128.00KiB (0.39%)
   /dev/sda3	  32.00MiB

Unallocated:
   /dev/sda3	  19.03GiB

According to ButterManager, this is the balance of data/metadata:


![Screenshot from 2021-11-28 07-31-08](https://user-images.githubusercontent.com/10172435/143769982-3c60df69-339f-48ee-90b1-880f8e4baba6.png)

Should I also request an R

![Screenshot from 2021-11-28 07-31-59](https://user-images.githubusercontent.com/10172435/143769999-d67d2c80-75cd-4fcc-aa33-311fb7fea07f.png)
MA?

**Comment by BlueGoliath** [comment]
Deleted more snapshots, SSD is now only 56% full.

But why the sudden bad sectors? Is this typical for SSDs?

**Comment by Zygo** [comment]
> Is btrfs not recommended for SSDs?

I doubt it.  The Famous Big social-media company runs btrfs on hundreds of thousands to millions of SSDs.

> To be clear, it's not a NVME drive but a 2.5 inch drive.

Are you sure it's a 970 EVO?  I have one, it's a NVME model.

> But why the sudden bad sectors?

Any storage device can fail at any time.

> Is this typical for SSDs?

For better consumer SSD models, yes.  There are 4 common SSD failure modes:
1.  Bad sectors, just like HDDs.  Errors show up in SMART and as UNC sector errors.  Better consumer SSDs do this.
2.  Silent data correction using FEC and redundant media in the drive.  Errors show up in SMART, if you can find them.  Drive typically doesn't report any errors, until one day it becomes read-only when it runs out of redundant media and can't maintain the illusion of perfection any more.  Some devices get slower as this happens.  Mostly these are devices rated for high-endurance usage.
3. Silent data corruption with no other indication of failure.  SMART doesn't report any errors because the drive itself can't tell it's failing.  More common in SD cards, but there are some cheap SSDs that do this.
4. The drive chooses a random day and becomes a brick on that day.  Any SSD can do this at any time, but it's more common in the low-end devices as they age.
