### ISSUE TITLE
why a file extents became more and more after the file transfer finished?

### ISSUE THREAD

**Issue by YangQing1989** [kdave/btrfs-progs#465]
I have a problem:
centos 7.3.1611
btrfs-progs v4.4.1

【local mount points and options】
Btrfs file system:
/dev/sdc on /mnt/data type btrfs (rw,noatime,compress=lzo,space_cache,autodefrag,subvolid=5,subvol=/)

Ext4 file system:
/dev/nvme0n1 on /mnt/m2ssd type ext4 (rw,relatime,data=ordered)

【the problem】
I copied a directory from /mnt/m2ssd to /mnt/data (using rsync -avP /mnt/m2ssd/src_dir /mnt/data)
Rsync shows that the transfer is complete. But I observed a strange phenomenon:
filefrag /mnt/data/src_dir/*
More and more extents are displayed in the file.

I know that Btrfs has a delay allocation mechanism, but isn't the original intention of this mechanism to reduce file fragmentation and make the file storage area more continuous?
How can it be more and more?
In fact, this file has only 17 extents under /mnt/m2ssd, but up to 28730 extents under /mnt/data

**Comment by adam900710** [comment]
Kernel version please.

Furthermore, considering the older btrfs-progs used, I doubt if the kernel is any better.

And if you're not using upstream/mainline kernel, I'm afraid you'd better to consult it with the distro.

**Comment by YangQing1989** [comment]
> Kernel version please.
> 
> Furthermore, considering the older btrfs-progs used, I doubt if the kernel is any better.
> 
> And if you're not using upstream/mainline kernel, I'm afraid you'd better to consult it with the distro.

Linux laplace 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by adam900710** [comment]
Yeah, too old kernel. No upstream 3.x kernel is ever maintained now. The oldest maintained upstream kernel is already v4.9.x now.

Please consult your distro for support on such old and heavily maintained kernel.

**Comment by YangQing1989** [comment]
Thank you very much. 

The reason why I'm investigating this problem is actually because I recently encountered a very strange problem. (it may have existed before, but I didn't notice it)
machine_A mounts the NFS share of our core file storage server (named Laplace).
machine_A downloads a text file (3GB) from the Internet daily. When Rsync is transmitted, it is actually downloaded in five minutes. But in the end, it will take more than ten minutes to show the real completion
(Rsync transferred the hidden file to the original file.)

[datauser@machine_A prod_bak]$ date;time rsync -avzP data_src_machine:/home/trade/xce/data/20220511 .
Wed May 11 16:19:03 CST 2022
receiving incremental file list
20220511/
20220511/20220511_cmb_tick_xce.csv
     62,345,585 100%   41.64MB/s    0:00:01 (xfr#1, to-chk=1/3)
20220511/20220511_tick_xce.csv
  3,224,452,797 100%   10.04MB/s    0:05:06 (xfr#2, to-chk=0/3)

sent 66 bytes  received 730,749,542 bytes  535,543.87 bytes/sec
total size is 3,286,798,382  speedup is 4.50

real    22m44.231s
user    0m38.146s
sys     0m10.031s

**As you can see, the actual transmission took only 5 minutes, but it actually took 22 minutes.
However, if I download a compressed package, this problem does not exist.**

**Comment by adam900710** [comment]
Sorry, there are too many things (NFS, rsync, performance, defragments, very old kernel) involved in this case, thus I can not provide much help.

But some things are interesting:

1. autodefrag
   That mount option will try to scan every modified file newer than certain generation.
   There are some bugs in recent (v5.1x) kernel involving that, but I'm not sure if ancient kernels are also involved.

2. Compress
   Compress will take extra CPU time, but normally it should be a big win as IO is always the bottleneck.
   Thus I don't believe compression is a problem.

   But compress will limit the extent size to 128K, thus it would cause tons of small extents, which will cause more metadata usage.

3. Rsync behavior
   I'm not sure if rsync will do fsync() in the end. If so and the file is very fragmented (I doubt, considering it's a cvs), it may
  cause too many data to be recorded into log tree, which itself may be a bottleneck (ironically, log tree itself is to speed up fsync).

So personally speaking, would you try the following things?

1. Use a mainline (v5.15 LTS for example) kernel to test again
   If you can reproduce, feel free to send a mail to btrfs mailling list, where you'll receive more feedback.
   Btrfs-progs issues are only for developers.
 
2. Try without compress mount option
3. Try without autodefrag mount option
4. Try scp instead of rsync
   AFAIK scp won't do any fsync() or extra check, but just copy the file in buffered write behavior.

**Comment by YangQing1989** [comment]
I removed the `autodefrag` and `compress` options and restarted the server
**Now the problem of slow download no longer exists.**

And I think I really don't need the compression function anymore (compression leads to too many extents, and our current metadata has reached hundreds of GB)
```
Metadata,RAID1: Size:342.00GiB, Used:181.67GiB
   /dev/sdc      342.00GiB
   /dev/sde      342.00GiB
```

In addition, I also built an additional test environment with the same version to simulate this problem, using the following three mounting options:
```
1、 noatime,compress=lzo
2、 noatime,autodefrag
3、 noatime,autodefrag,compress=lzo
```
The rsync download didn't have the problem I initially fed back. It's really weird~

Thank you very much for your help and advice. 
Heartfelt thanks~
*(next time I'll go somewhere else to ask questions, not here)*

**Comment by kdave** [comment]
Thanks Qu.

> (next time I'll go somewhere else to ask questions, not here)

From what I've seen people ask where they think they can get the answer and for btrfs there are several places. I don't mind if it's here, sometimes it's not clear where a potential problem might be (kernel, progs, how to do things) so don't worry, here the developers or interested people may know, unlike in some other forums, too many of them.
