### ISSUE TITLE
path-util.c:(.text+0xbc0): multiple definition of `path_is_mount_point'; common/path-utils.o:path-utils.c:(.text+0x290): first defined here

### ISSUE THREAD

**Issue by tuananh** [kdave/btrfs-progs#611]
can someone help me on why im having this error 

```
/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib/libudev.a(path-util.o): in function `path_is_mount_point':
path-util.c:(.text+0xbc0): multiple definition of `path_is_mount_point'; common/path-utils.o:path-utils.c:(.text+0x290): first defined here
```

**Comment by kdave** [comment]
Please post what build environment you use (distro, libc, compiler version, linker if not using the default one) and what build command exactly. I don't see anything strange with path-utils.c in particuluar, the function is defined in a .c file, the object file is mentioned only once in the linked file list.

**Comment by kdave** [comment]
Oh I see what's wrong, it's a name clash of libudev and path-utils.c, same function `path_is_mount_point`.

**Comment by kdave** [comment]
Are you building static `btrfs` with static libudev? This is not supported so far because static libudev is not common. Also `path_is_mount_point` is not a static function but still not exported to the library so for a dynamic library it's not visible. When linking directly with libudev.a the symbol is defined as weak same as the btrfs' one and the names clash. A quick fix is to rename it in btrfs-progs but before making it a permanent fix I'd like to see if there's another way.

**Comment by tuananh** [comment]
> Are you building static btrfs with static libudev?
yes.

so is it recommended to have it disabled?

**Comment by kdave** [comment]
We can make it work, I'll rename the function so it does not clash.

**Comment by kdave** [comment]
Fix pushed to devel, please test and let me know if there are other problems with static libudev.
