### ISSUE TITLE
Metadata allocation too big

### ISSUE THREAD

**Issue by meravsapir** [kdave/btrfs-progs#835]
## Problem ##
A btrfs file system of about 1.75TB where metadata is allocated 474GB but only 1.5GB used, only 78GB data used and 1.2TB unallocated.
Balance and scrub didn't help free allocated metadata and "btrfs balance" on the metadata failed on "no space left on device"

## Instance data ##
kernel version: 3.10.0-1062.1.2.el7.x86_64
OS type: CentOS Linux 7 (Core)
btrfs-progs: v4.9.1

## btrfs filesystem usage ##
"Overall": {
    "Device size": "1.74TiB",
    "Device allocated": "552.03GiB",
    "Device unallocated": "1.20TiB",
    "Device missing": "0.00B",
    "Used": "78.47GiB",
    "Free (estimated)": "1.20TiB (min: 1.20TiB)",
    "Data ratio": "1.00",
    "Metadata ratio": "1.00",
    "Global reserve": "149.28MiB (used: 0.00B)"
  },
  "Data,single": {
    "Size": "78.00GiB",
    "Used": "76.97GiB",
    "/dev/nvme9n1": "78.00GiB"
  },
  "Metadata,single": {
    "Size": "474.00GiB",
    "Used": "1.50GiB",
    "/dev/nvme9n1": "474.00GiB"
  },
  "System,single": {
    "Size": "32.00MiB",
    "Used": "96.00KiB",
    "/dev/nvme9n1": "32.00MiB"
  },
  "Unallocated": {
    "/dev/nvme8n1": "67.00GiB",
    "/dev/nvme9n1": "1.13TiB"
  }

## Actions taken ##
btrfs balance start -musage=10 <mount_path>
ERROR: error during balancing '<mount_path>': No space left on device
There may be more info in syslog - try dmesg | tail

btrfs balance start -musage=5 <mount_path>
Done, had to relocate 1010 out of 1099 chunks

btrfs balance start -musage=10 <mount_path>
Done, had to relocate 1010 out of 1099 chunks
**why is the output for musage-10 is the same as musage=5? weren't these chunks already relocated?**

Tried running with higher musage numbers but no changes and then got  No space left on device.
Then, trying lower number again if failed with "No space left on device", event with musage=0.

btrfs scrub start -b <mount_path>
took it a few minutes but it finished without affecting the metadata allocated size.

**Comment by eliran-zada-zesty** [comment]
Had the same issue... can someone help with this?

**Comment by Zygo** [comment]
> kernel version: 3.10.0-1062.1.2.el7.x86_64

The issues you are having were fixed a decade ago.  All you have to do is upgrade.

**Comment by meravsapir** [comment]
Thanks @Zygo.
Can you please point me to the relevant changes done in order to resolve this issue? 
Unfortunately, our company's OS upgrade policy is very cumbersome so I need to come with a strong argument for the upgrade. I'm afraid this being a very old version and even EOL version is not considered strong enough.

**Comment by adam900710** [comment]
I'd say, if you're already using an EOL and heavily backported kernel, you should ask for help from the vendor.
(And I'm going to say, Redhat doesn't even support Btrfs for their enterprise systems).

For upstream we only support upstream supported kernels.

**Comment by Zygo** [comment]
Block group allocation and allocation in general have been modified many times since 3.10 was released in 2013.  In some cases, comprehensive redesign of btrfs components removes a bug that is not known to exist at the time the change is made, so attribution is only possible if the bug is discovered by running bisection on old and new kernels, then locating the points where the bug is introduced and removed--a significant effort that isn't often spent in service of old kernels.  Over 100 bugs are known to have existed in 3.10 so far (based on the number of kernel commit `Fixes:` tags which remove them), but new bugs that affect kernel 3.10 continue to be discovered to this day, so 100 is likely an undercount.

Some of the more significant changes related directly to allocation (the ones I have direct experience with):
- Empty block group reclaim was added in [3.18](https://btrfs.readthedocs.io/en/latest/Feature-by-version.html)
- [4.4](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0584f718ed1f351fca5047a4b1ebba9b5ea41215) and [4.14](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=583b723151794e2ff1691f1510b4e43710293875) had significant allocator behavior changes
- Auto block group reclaim for user-settable threshold added in 5.19
- Scrub used to trigger spurious empty metadata chunk allocations.  It stopped happening somewhere between 4.14 and 5.0, but I didn't do the bisection to find specific commits.

I would not recommend attempting using btrfs on kernel versions before 4.14, as this is the oldest LTS kernel that has backported fixes for several known bugs that lead to [data corruption, crashes, hangs, and catastrophic filesystem failures](https://zygo.github.io/bees/btrfs-kernel.html).  Many of these bugs date back to 2011 or earlier, predating 3.10.  Running an older kernel has no practical use except to rediscover vintage bugs.

**Comment by kdave** [comment]
Thanks everybody for the answers, I don't have anything to add, 3.10 is out of scope.
